### ISSUE TITLE
No function can release the memory of a number_t object?

### ISSUE THREAD

**Issue by fenggang-ok** [brotherbeer/mynum#15]
If an integer object is very large, after using it, I want to release its memory, I used 'set_zero', but it just set the meaning of the object to zero, the memory was not released...

**Comment by brotherbeer** [comment]
use ~number_t() please

**Comment by fenggang-ok** [comment]
> use ~number_t() please

call the destructor explicitly? This, IMHO, is so weird...

**Comment by fenggang-ok** [comment]
add a function named 'clear' maybe better...

**Comment by brotherbeer** [comment]
> add a function named 'clear' maybe better...

OK, I'll do it, my friend
