### ISSUE TITLE
How to get the absolute value of a signed integer?

### ISSUE THREAD

**Issue by brotherbeer** [brotherbeer/mynum#6]
Really a sample question, but it's worth discussing, it's easy to write a function to do that:

``` C++
int __abs(int x)
{
    return x > 0? x: -x;
}
```

It needs conditional judgment and jump instructions, **is there a quicker way to do it?**
I'm aware of that using pure bit operations can also finish the same function:

``` C++
int __abs(int x)
{
    int y = x >> 31;
    return (x + y) ^ y;
}
```

">>" means signed right shift, so when _x_ >= 0, _y_ is zero, when _x_ < 0, _y_ is -1 (0xFFFFFFFF)
when _x_ >= 0, (_x_ + _y_) ^ _y_ is _x_, when _x_ < 0, (_x_ + _y_) ^ _y_ means ~(_x_ - 1), no other than the absolute value.

On older machines, bit operations are much faster than conditional judgments and jumps, but this is not sure on the current popular machines.
If you have a better method, please tell me :)

**Comment by fenggang-ok** [comment]
If use GCC, _x > 0? x: -x_ maybe the best
```c++
int abs(int x)
{
    return x > 0? x: -x;
}
```
GCC O2 disassembly on MAC, two instructions finish the job(neg, cmovl)
```asm
    push       rbp
    mov        rbp, rsp
    mov        eax, edi
    neg        eax
    cmovl      eax, edi
    pop        rbp
    ret
```
VC released disassembly on Windows
```asm
    13FCA1000  test        ecx,ecx 
    13FCA1002  jg          abs+6 (13FCA1006h) 
    13FCA1004  neg         ecx    
    13FCA1006  mov         eax,ecx 
```
The second method
```c++
int abs(int x)
{
    int y = x >> 31;
    return (x + y) ^ y;
}
```
GCC O2 assembly code on MAC, three instructions finish the job(sar, lea, xor)
```asm
    push       rbp
    mov        rbp, rsp
    mov        ecx, edi
    sar        ecx, 0x1f
    lea        eax, dword [ds:rdi+rcx]
    xor        eax, ecx
    pop        rbp
    ret         
```
VC released disassembly on Windows
    same to GCC
